### ISSUE TITLE
Durandal JS wrapShim Configration with grunt issue

### ISSUE THREAD

**Issue by malaythecool** [RainerAtSpirit/HTMLStarterKitPro#3]
I am trying to do wrapShim for external js file which is not coming under AMD and so can not include code under same define on code generation via grrunt. So, where exactly i should put wrapShim: true i am not getting.

Following is basic configuration code fraction for grunt durandal where i innserted wrapShim

```
durandal: {
                main: {
                    src: ['app/**/*.*', 'lib/durandal/**/*.js'],
                    options: {
                        name: '../lib/require/almond-custom',
                        baseUrl: requireConfig.baseUrl,
			wrapShim: true,
                        mainPath: 'app/main',
                        paths: mixIn({}, requireConfig.paths, { 'almond': '../lib/require/almond-custom.js' }),
                        exclude: [],
                        optimize: 'none',
                        out: 'build/app/main.js'
                    }
                }
            },
```

**Comment by RainerAtSpirit** [comment]
Sorry to say, but this repo is four years old and Durandal is no longer maintained. 
You might want to take a look at http://aurelia.io/ instead.
